### ISSUE TITLE
CRISPRme gnomAD data

### ISSUE THREAD

**Issue by ShanSabri** [pinellolab/CRISPRme#3]
Hi @samuelecancellieri and @kclem -- Is it possible to post links to the converted CRISPRme gnomAD data (e.g. `gnomad.genomes.v3.1.sites.chr*.collapsed.vcf.gz`)? 

Thank you!

**Comment by ShanSabri** [comment]
Can data be sources from this file? https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/vcf/gnomad.genomes.r3.0.sites.vcf.gz

**Comment by samuelecancellieri** [comment]
Hi @ShanSabri, we do not collect the converted VCF data due to their dimension, but you can download the original VCF files from here, https://gnomad.broadinstitute.org/downloads
you need to download the gnomADv3 dataset,
the link to chr1 VCF, https://storage.googleapis.com/gcp-public-data--gnomad/release/3.1.2/vcf/genomes/gnomad.genomes.v3.1.2.sites.chr1.vcf.bgz
and save them into a directory in the vcf folder of CRISPRme, naming the directory with the name of the genome e.g. hg38_gnomAD.
After that you can process the gnomAD files with the tool, gnomAD-converter from CRISPRme package,
calling something like this,
crisprme.py gnomAD-converter --gnomAD_VCFdir VCFs/hg38_gnomAD/ --samplesID samplesIDs/hg38_gnomAD.samplesID.txt --thread 1
the first one is the path to VCF folder containing gnomAD VCFs
the second one is the sampleID created for gnomAD (I'm attaching it to this response)
[hg38_gnomAD.samplesID.txt](https://github.com/pinellolab/CRISPRme/files/8067811/hg38_gnomAD.samplesID.txt)
the last one is the number of concurrent threads to use, one thread processes one VCF file.

Hope this answer help you with this task, if you have any other problem or question, don't hesitate to ask.

Thanks a lot for using CRISPRme.

**Comment by samuelecancellieri** [comment]
> Hi @samuelecancellieri -Thank you for getting back. I'm in the process of downloading these data and will let you know if I hit any sort of road block in the conversion process. I'm also interested in running CRISPRme with UK BioBank data. Is that possible out of the box, or is a VCF conversion needed?

Hi, I don't know if the BioBank VCFs are similar to 1000G or HGDP VCFs (VCF v4.3), in that case it should work with no further conversion, if not, you need to convert the data into VCFv4.3 format.
The only file you will need to create personally, is the sampleID file, in the same format as the files provided in the test_package (hg38_1000G.samplesID.txt or hg38_HGDP.samplesID.txt). This file contains the info for each sample reported in the VCF columns.
If you need any help for this step, do not hesitate to contact me.

Thanks.

**Comment by ShanSabri** [comment]
Hi @samuelecancellieri - I've finished VCF conversion but when I run CRISPRme I notice the error log fill: 
```
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr3_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr3_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr3_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr4_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr4_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr4_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr9_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr9_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr9_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr12_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr12_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr12_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr13_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr13_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr13_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr21_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr21_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr21_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr18_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr18_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr18_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
tail: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr6_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
head: cannot open '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr6_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt' for reading: No such file or directory
rm: cannot remove '/home/ubuntu/CRISPRme/crisprme_test/Results/sg94_1000G_HGDP_GNOMAD/fakechr6_20bp-NGG-spCas9.txt_guides.txt_6_2_2.targets.txt': No such file or directory
Traceback (most recent call last):
  File "./new_simple_analysis.py", line 353, in <module>
    snpToReplace, sampleSet, rsID, AF_var, snpInfo = retrieveFromDict(pos_c+int(split[4]))
  File "./new_simple_analysis.py", line 168, in retrieveFromDict
    entry = mydict[current_chr+','+str(chr_pos+1)]
NameError: name 'mydict' is not defined
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "./new_simple_analysis.py", line 353, in <module>
    snpToReplace, sampleSet, rsID, AF_var, snpInfo = retrieveFromDict(pos_c+int(split[4]))
  File "./new_simple_analysis.py", line 168, in retrieveFromDict
    entry = mydict[current_chr+','+str(chr_pos+1)]
NameError: name 'mydict' is not defined
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "./new_simple_analysis.py", line 353, in <module>
    snpToReplace, sampleSet, rsID, AF_var, snpInfo = retrieveFromDict(pos_c+int(split[4]))
  File "./new_simple_analysis.py", line 168, in retrieveFromDict
    entry = mydict[current_chr+','+str(chr_pos+1)]
NameError: name 'mydict' is not defined
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
...
```

Any ideas?

**Comment by ShanSabri** [comment]
I've converted the GnomAD VCF and when I run using the test data on these 3 sets of VCFs I get an error: 
```
Traceback (most recent call last):
  File "./new_simple_analysis.py", line 353, in <module>
    snpToReplace, sampleSet, rsID, AF_var, snpInfo = retrieveFromDict(pos_c+int(split[4]))
  File "./new_simple_analysis.py", line 168, in retrieveFromDict
    entry = mydict[current_chr+','+str(chr_pos+1)]
NameError: name 'mydict' is not defined
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "./adjust_cols.py", line 20, in <module>
    cols.remove('CFD_ref')
ValueError: list.remove(x): x not in list
```

Any ideas?

**Comment by samuelecancellieri** [comment]
Hi @ShanSabri, seems a problem with the dictionaries created during the VCF reading phase, can you check what is present in the Dictionaries directory in the main CRISPRme folder?

**Comment by ShanSabri** [comment]
Hm it looks like there are no dictionaries because the`dictionaries_hg38_gnomAD` `log_indels_hg38_gnomAD` directories are empty.  

Here's the format of the converted VCFs, `gnomad.genomes.v3.1.2.sites.chr21.collapsed.vcf.gz` for examples: 
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##hailversion=0.2.77-684f32d73643
##FILTER=<ID=AC0,Description="Allele count is zero after filtering out low-confidence genotypes (GQ < 20; DP < 10; and AB < 0.2 for het calls)">
##FILTER=<ID=AS_VQSR,Description="Failed VQSR filtering thresholds of -2.7739 for SNPs and -1.0606 for indels">
##FILTER=<ID=InbreedingCoeff,Description="InbreedingCoeff < -0.3">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Alternate allele count">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles">
##INFO=<ID=AF,Number=A,Type=Float,Description="Alternate allele frequency">
##INFO=<ID=popmax,Number=A,Type=String,Description="Population with maximum allele frequency">
...
...
##contig=<ID=chrY,length=57227415,assembly=gnomAD_GRCh38>
##contig=<ID=chrM,length=16569,assembly=gnomAD_GRCh38>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Sample Collapsed Genotype">
##bcftools_normVersion=1.12+htslib-1.12
##bcftools_normCommand=norm -m+ -O z -o /crisprme_data/gnomad.genomes.v3.1.2.sites.chr21.collapsed.vcf.gz /crisprme_data/gnomad.genomes.v3.1.2.sites.chr21.vcf.gz; Date=Thu Feb 17 13:45:29 2022
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  afr     ami     amr     asj     eas     fin     nfe     mid     sas     oth
chr21   5030240 rs1185110752    AC      A       .       PASS    AF=0.00423504   GT      0/0     0/0     0/0     0/0     0/1     0/0     0/1     0/0     0/1     0/0
chr21   5030526 .       G       A       .       PASS    AF=8.80379e-05  GT      0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/0
chr21   5030568 .       GACA    G       .       PASS    AF=2.79689e-05  GT      0/0     0/0     0/1     0/0     0/0     0/0     0/1     0/0     0/0     0/0
chr21   5030569 .       A       G       .       PASS    AF=9.33097e-06  GT      0/0     0/0     0/1     0/0     0/0     0/0     0/0     0/0     0/0     0/0
chr21   5030601 rs1370167485    T       TA      .       PASS    AF=0.00017347   GT      0/1     0/0     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0
chr21   5030615 .       A       C       .       PASS    AF=8.42162e-06  GT      0/0     0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0     0/0
chr21   5030619 rs1331293723    G       A       .       PASS    AF=4.18908e-05  GT      0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/0     0/1     0/0
...
...
chr21	46699956	rs1569175321	T	TA	.	PASS	AF=0.000605694	GT	0/0	0/0	0/1	0/0	0/0	0/0	0/0	0/0	0/0	0/0
chr21	46699957	.	GGGTTA	G	.	PASS	AF=0.0555556	GT	0/1	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0
chr21	46699965	rs1434216090	GT	G	.	PASS	AF=0.0833333	GT	0/0	0/0	0/1	0/0	0/0	0/0	0/0	0/0	0/0	0/0
chr21	46699972	rs1258534132	T	G	.	PASS	AF=0.1	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/1	0/0	0/0	0/0
chr21	46699973	.	TA	T	.	PASS	AF=0.1	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/1	0/0	0/0	0/0
chr21	46699974	.	A	T	.	PASS	AF=0.0833333	GT	0/0	0/0	0/0	0/0	0/0	0/1	0/0	0/0	0/0	0/0
```

**Comment by samuelecancellieri** [comment]
Hi @ShanSabri, that's strange, the VCF converted file seems fine, just a question, did you remove the original .bgz files from gnomAD from the VCF directory? Keeping only the collapsed ones? The software does not recognize the gnomAD file as wrong and tries to process them anyway, causing possible errors, I'm thinking that maybe the process of creating the dictionaries got somehow messed up. I suggest you to remove the .bgz files from the VCF directory, keep only the collapsed VCFs and if you do not have any other important result or preprocessed genome, you can run the clean_all.sh script included in the crisprme_package, that takes care of reset any directory to first installation status. If you want to preserve any result or genome already processed, just copy them elsewhere and then run the clean_all script.

If you encounter any other error, don't hesitate to contact me.
I will leave here my mail for more direct contact,
samuele.cancellieri@univr.it

Best,
Samuele

**Comment by ShanSabri** [comment]
> did you remove the original .bgz files from gnomAD from the VCF directory? Keeping only the collapsed ones? 
Yep, I have the original `*.bgz` VCFs in another directory and only have the collapsed ones under `VCFs/hg38_gnomAD/`

Let me try to run the clean_up and reset and circle back on this. Appreciate all the help thus far!

**Comment by ShanSabri** [comment]
Running the cleanup script followed by a re-run using your test data seemed to work. Thanks for the help!
