### ISSUE TITLE
run failed v2.1.1

### ISSUE THREAD

**Issue by dsantesmasses** [pinellolab/CRISPRme#31]
Hi!

I am trying to run CRISPRme on chr22 with no VCF files, but the run fails with the error below. Is there any required parameter that I might be missing? Thanks!

**To Reproduce**
```
$ crisprme.py complete-search --genome Genomes/hg38_chr22/ --guide sg1617.txt --pam PAMs/20bp-NGG-SpCas9.txt --bMax 2 --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output output --thread 12
--annotation not used
Launching job /data2/crisprme_test/Results/output. The stdout is redirected in log_verbose.txt and stderr is redirected in log_error.txt
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/crisprme/bin/crisprme.py", line 934, in <module>
    complete_search()
  File "/home/ubuntu/miniconda3/envs/crisprme/bin/crisprme.py", line 673, in complete_search
    raise OSError(f"\nCRISPRme run failed! See {os.path.join(outputfolder, 'log_error.txt')} for details\n")
OSError:
CRISPRme run failed! See /data2/crisprme_test/Results/output/log_error.txt for details

$ head -50 /data2/crisprme_test/Results/output/log_error.txt
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3081, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rsID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./remove_n_and_dots.py", line 29, in <module>
    chunk['rsID'] = chunk['rsID'].str.replace('.', 'NA')
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3083, in get_loc
    raise KeyError(key) from err
KeyError: 'rsID'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3081, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rsID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./remove_n_and_dots.py", line 29, in <module>
    chunk['rsID'] = chunk['rsID'].str.replace('.', 'NA')
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3083, in get_loc
    raise KeyError(key) from err
KeyError: 'rsID'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/crisprme/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3081, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rsID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
```

If running CRISPRme via command line, type the command line call to CRISPRme returning the error

If running CRISPRme via the website, please fill the form below:
1. Spacer sequences

2. Cas protein

3. PAM

4. Genome

5. Variants dataset (OPTIONAL)

6. Thresholds 
Mismatches:
DNA Bulges:
RNA Bulges:

7. Base editing (OPTIONAL)
Start:
Stop:
Nucleotide:

8. Annotation

**Expected behavior**

**Screenshots**
If running CRISPRme via website, add screenshots to help explain your problem.

**Environment (please complete the following information, ONLY applicable if running CRISPRme via command line):**
- Python version
- CRISPRme version
- CRISPRitz version
- axel version
- gdown version
- numpy version
- dash version
- dash-bootstrap-components version
- dash-core-components version
- dash-daq version
- dash-html-components version
- dash-renderer version
- dash-table version
- flask version
- flask-caching version
- flask-compress version
- fontconfig version
- freetype version
- future version
- gettext version
- gunicorn version
- werkzeug version
- pandas version

**Additional context**

**Comment by samuelecancellieri** [comment]
Hello @dsantesmasses 

I've tested the version 2.1.1 and encountered the bug you reported, I'm currently investigating the cause.
So I'm suggesting you to downgrade CRISPRme to version 2.1.0 until the bug is resolved.

The two versions produced the same exact results, so you will be able to compare any data produced with either 2.1.0 or 2.1.1

Sorry for this inconvenience.
Let me know if this temporary solution, it's fine.

Best,
