### ISSUE TITLE
Not getting expected Spacer+Pam Sequence in output files - rerun with guide sequence (no NNN) only fails.

### ISSUE THREAD

**Issue by SaraJeanne08** [pinellolab/CRISPRme#76]
**Describe the bug**
After running CRISPRme initially I noticed that the output files for the Spacer+Pam sequence includes NNN instead of the designated PAM sequence.  I am not sure if this is expected behavior when following the test run input file formats.

I want to search the specified genome by the input PAM sequence - not NNN. So I tried re-running with your test provided guide file but without the NNN at the end. I got the following error in the log file:

`Traceback (most recent call last):
  File "/opt/conda/opt/crisprme/PostProcess/./radar_chart_dict_generator.py", line 168, in <module>
    fillDict(guide, guideDict, motifDict)
  File "/opt/conda/opt/crisprme/PostProcess/./radar_chart_dict_generator.py", line 121, in fillDict
    if guide[count] == 'N':
IndexError: string index out of range
ERROR: Radar chart generation on reference CFD report failed!`

How do I search with the guide sequence + specified input PAM (not NNN)?
 
**To Reproduce**

docker run -v crisprme_test/:/DATA -w /DATA -i pinellolab/crisprme crisprme.py complete-search --genome Genomes/hg38/ --guide sg1617_update.txt --pam PAMs/20bp-NGG-spCas9.txt --sorting-criteria-scoring mm+bulges --sorting-criteria mm,bulges --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output test.sg.NGG.updateGuide --thread 32

Here is the guide updated sequence I used (sg1617): 

CTAACAGTTGCTTTTATCAC

Here is the specified PAM sequence txt input file I used:
NNNNNNNNNNNNNNNNNNNNNGG 3

**Expected behavior**
successfully completed run with input guide sequence and specified PAM sequence in output files (spacer+pam) column:
CTAACAGTTGCTTTTATCACNGG

**Environment (please complete the following information, ONLY applicable if running CRISPRme via command line):**

Running most recent docker image for crisprme 2.1.6: when installing via docker pull pinellolab/crisprme

**Comment by lindayqlin** [comment]
Hi Sara,

Thank you for using CRISPRme! My apologies for the late reply on our end.

I believe the issue may be that CRISPRme expects users to always input their guide RNA sequence along with `N`s where their PAM will be, designed to mean "Please search for this guide RNA sequence with a PAM in this position." Then, we expect users to input a separate PAM file with `N`s everywhere except the positions you would like restricted in your PAM search, so the last two `GG` in your case. 

We designed our expected inputs in this manner to allow for maximum flexibility since various Cas systems have PAMs in different locations (some at the 5' rather then 3' end for instance), so we require users to tell us where to expect the PAM via `N`s in the `--guide` file. Hopefully this makes some sense?

In your case, if you input `CTAACAGTTGCTTTTATCACNNN` for `--guide` along with your PAM file above, CRISPRme will perform its search with a `NGG` PAM as specified in your PAM file, not `NNN`. The `NNN` following the guide RNA sequence there solely serves to indicate where you expect your PAM to be, while CRISPRme gets the actual sequence of your desired PAM from your `--pam` input.

Hope this helps!
Linda
